# Copyright 2025 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CI:
  - changed-files:
      - any-glob-to-any-file:
        - '.github/**'
        - 'docker/**'

github_actions:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - '**/*.mdx'
          - 'docs/**'

examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'

tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**'

sensors:
  - changed-files:
      - any-glob-to-any-file: 'src/lerobot/cameras/**'

configuration:
  - changed-files:
      - any-glob-to-any-file: 'src/lerobot/configs/**'

dataset:
  - changed-files:
      - any-glob-to-any-file: 'src/lerobot/datasets/**'

evaluation:
  - changed-files:
      - any-glob-to-any-file: 'src/lerobot/envs/**'

robots:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/lerobot/teleoperators/**'
          - 'src/lerobot/robots/**'
          - 'src/lerobot/motors/**'

policies:
  - changed-files:
      - any-glob-to-any-file: 'src/lerobot/policies/**'

processor:
  - changed-files:
      - any-glob-to-any-file: 'src/lerobot/processor/**'
