# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: franka_api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ranka_api.proto\x12\x06\x66ranka\"N\n\nJointState\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\x10\n\x08position\x18\x02 \x03(\x01\x12\x10\n\x08velocity\x18\x03 \x03(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x04 \x03(\x01\"W\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\n\n\x02qx\x18\x04 \x01(\x01\x12\n\n\x02qy\x18\x05 \x01(\x01\x12\n\n\x02qz\x18\x06 \x01(\x01\x12\n\n\x02qw\x18\x07 \x01(\x01\"P\n\x06Wrench\x12\n\n\x02\x66x\x18\x01 \x01(\x01\x12\n\n\x02\x66y\x18\x02 \x01(\x01\x12\n\n\x02\x66z\x18\x03 \x01(\x01\x12\n\n\x02tx\x18\x04 \x01(\x01\x12\n\n\x02ty\x18\x05 \x01(\x01\x12\n\n\x02tz\x18\x06 \x01(\x01\"\x07\n\x05\x45mpty\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd8\x01\n\rFrankaService\x12\x32\n\rGetJointState\x12\r.franka.Empty\x1a\x12.franka.JointState\x12)\n\nGetEEFPose\x12\r.franka.Empty\x1a\x0c.franka.Pose\x12*\n\tGetWrench\x12\r.franka.Empty\x1a\x0e.franka.Wrench\x12<\n\x0eSetJointTarget\x12\x12.franka.JointState\x1a\x16.franka.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'franka_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOINTSTATE']._serialized_start=28
  _globals['_JOINTSTATE']._serialized_end=106
  _globals['_POSE']._serialized_start=108
  _globals['_POSE']._serialized_end=195
  _globals['_WRENCH']._serialized_start=197
  _globals['_WRENCH']._serialized_end=277
  _globals['_EMPTY']._serialized_start=279
  _globals['_EMPTY']._serialized_end=286
  _globals['_STATUSRESPONSE']._serialized_start=288
  _globals['_STATUSRESPONSE']._serialized_end=338
  _globals['_FRANKASERVICE']._serialized_start=341
  _globals['_FRANKASERVICE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
