"""Data packaging for self-improvement pipeline v2.

Convert eval rollout trajectories into a proper LeRobotDataset for
continued training via lerobot-train.
"""

import logging
import shutil
from pathlib import Path

import numpy as np
import torch

from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import DEFAULT_IMAGE_PATH

logger = logging.getLogger(__name__)

# Keys auto-generated by LeRobotDataset — never pass to add_frame.
_METADATA_KEYS = frozenset({"timestamp", "frame_index", "episode_index", "index", "task_index"})

# Features from the pretrain dataset that are NOT needed for training.
# These are reward/done signals; the policy only uses observation.* and action.
_EXCLUDE_FEATURE_PREFIXES = ("next.",)


def _training_features(features: dict) -> dict:
    """Keep only training-relevant features (observation.*, action)."""
    return {
        k: v for k, v in features.items()
        if not any(k.startswith(p) for p in _EXCLUDE_FEATURE_PREFIXES)
    }


def _features_as_images(features: dict) -> dict:
    """Return a copy of *features* with ``"video"`` dtypes replaced by ``"image"``
    and shape lists converted to tuples (JSON stores lists, but validation expects tuples)."""
    out = {}
    for k, v in features.items():
        entry = dict(v)
        if entry.get("dtype") == "video":
            entry["dtype"] = "image"
        if isinstance(entry.get("shape"), list):
            entry["shape"] = tuple(entry["shape"])
        out[k] = entry
    return out


def _to_hwc(val: torch.Tensor | np.ndarray) -> torch.Tensor | np.ndarray:
    """Transpose a CHW image tensor/array to HWC for ``add_frame`` validation."""
    if isinstance(val, torch.Tensor) and val.ndim == 3 and val.shape[0] in (1, 3, 4):
        return val.permute(1, 2, 0)
    if isinstance(val, np.ndarray) and val.ndim == 3 and val.shape[0] in (1, 3, 4):
        return val.transpose(1, 2, 0)
    return val


# ──────────────────────────────────────────────────────────────────
# Online dataset from eval rollouts
# ──────────────────────────────────────────────────────────────────

def episodes_to_lerobot_dataset(
    episodes: list[dict],
    repo_id: str,
    root: Path,
    fps: int,
    features: dict,
    task_description: str,
    bc_mask_mode: str = "none",
) -> LeRobotDataset:
    """Convert eval rollout episodes into a :class:`LeRobotDataset` on disk.

    Args:
        episodes: List of episode dicts (from :func:`episodes_from_eval_info`).
            Each dict has ``observations`` (dict of tensors), ``actions``
            (tensor), ``rewards`` (tensor), and ``success`` (bool).
        repo_id: Dataset identifier, e.g. ``"self_improve/online_iter0"``.
        root: Local directory to store the dataset.
        fps: Frames per second (must match pretrain dataset).
        features: Feature spec from pretrain dataset.
        task_description: Task string for each frame.
        bc_mask_mode: ``"none"`` = no mask column, ``"failure"`` = mask
            failure episodes (bc_loss_mask=0 for failures, 1 for successes).

    Returns:
        The created :class:`LeRobotDataset`.
    """
    ds_features = _training_features(_features_as_images(features))
    if bc_mask_mode != "none" and "bc_loss_mask" not in ds_features:
        ds_features["bc_loss_mask"] = {"dtype": "float32", "shape": (1,), "names": None}

    if root.exists():
        shutil.rmtree(root)

    dataset = LeRobotDataset.create(
        repo_id=repo_id,
        fps=fps,
        features=ds_features,
        root=root,
        use_videos=False,
    )

    # Pre-create image directories for every episode so that add_frame
    # never hits a missing-directory error (upstream add_frame only does
    # mkdir on frame_index==0 and write_image silently swallows errors).
    image_keys = [k for k, v in ds_features.items() if v.get("dtype") in ("image", "video")]
    for ep_idx in range(len(episodes)):
        for img_key in image_keys:
            img_dir = root / Path(
                DEFAULT_IMAGE_PATH.format(image_key=img_key, episode_index=ep_idx, frame_index=0)
            ).parent
            img_dir.mkdir(parents=True, exist_ok=True)

    n_success, n_fail = 0, 0
    for episode in episodes:
        obs = episode["observations"]
        actions = episode["actions"]
        success = episode["success"]
        n_frames = actions.shape[0]

        if success:
            n_success += 1
        else:
            n_fail += 1

        bc_mask_val = 1.0 if success else (0.0 if bc_mask_mode == "failure" else 1.0)

        for t in range(n_frames):
            frame: dict = {"task": task_description}
            for key, val in obs.items():
                if key in ds_features:
                    v = val[t]
                    if ds_features[key].get("dtype") in ("image", "video"):
                        v = _to_hwc(v)
                    frame[key] = v
            frame["action"] = actions[t]
            if bc_mask_mode != "none":
                frame["bc_loss_mask"] = np.array([bc_mask_val], dtype=np.float32)
            dataset.add_frame(frame)

        dataset.save_episode()

    dataset.finalize()
    logger.info(
        "Created online dataset: %d episodes (%d success, %d fail), %d frames at %s",
        len(episodes), n_success, n_fail, dataset.num_frames, dataset.root,
    )
    return dataset


# ──────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────

def episodes_from_eval_info(info: dict) -> list[dict]:
    """Split flat ``eval_policy`` output into per-episode dicts.

    Args:
        info: Return value of ``eval_policy(return_episode_data=True)``.

    Returns:
        List of dicts, each with ``observations`` (dict of tensors),
        ``actions`` (tensor), ``rewards`` (tensor), ``success`` (bool).
    """
    ep_data = info["episodes"]
    per_ep = info["per_episode"]

    episodes: list[dict] = []
    for ep_info in per_ep:
        ep_idx = ep_info["episode_ix"]
        mask = ep_data["episode_index"] == ep_idx

        obs: dict[str, torch.Tensor] = {}
        for key in ep_data:
            if key.startswith("observation.") and not key.endswith("_is_pad"):
                obs[key] = ep_data[key][mask]

        actions = ep_data["action"][mask]
        rewards = ep_data["reward"][mask] if "reward" in ep_data else torch.zeros(mask.sum())

        episodes.append({
            "observations": obs,
            "actions": actions,
            "rewards": rewards,
            "success": bool(ep_info["success"]),
        })
    return episodes


def get_pretrain_info(
    pretrain_repo_id: str,
    pretrain_root: str | Path | None = None,
) -> dict:
    """Load pretrain dataset metadata without reading frame data.

    Returns dict with ``fps``, ``features``, ``num_episodes``,
    ``num_frames``, and ``task_description``.
    """
    from lerobot.datasets.lerobot_dataset import LeRobotDatasetMetadata

    meta = LeRobotDatasetMetadata(pretrain_repo_id, root=pretrain_root)
    task_desc = ""
    if meta.tasks is not None and len(meta.tasks) > 0:
        task_desc = meta.tasks.iloc[0].name
    return {
        "fps": meta.fps,
        "features": dict(meta.features),
        "num_episodes": meta.total_episodes,
        "num_frames": meta.total_frames,
        "task_description": task_desc,
    }


def read_training_step(checkpoint_dir: str | Path) -> int:
    """Read the training step from a checkpoint directory."""
    from lerobot.utils.train_utils import load_training_step
    from lerobot.utils.constants import TRAINING_STATE_DIR

    training_state_dir = Path(checkpoint_dir) / TRAINING_STATE_DIR
    return load_training_step(training_state_dir)
