from typing import Protocol


class Robot(Protocol):
    def init_teleop(self): ...
    def run_calibration(self): ...
    def teleop_step(self, record_data=False): ...
    def capture_observation(self): ...
    def send_action(self, action): ...
