# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sac.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "sac.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tsac.proto\x12\x03sac")\n\nModelState\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02""\n\x0cModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t2{\n\rTensorService\x12:\n\x12StreamModelUpdates\x12\x11.sac.ModelRequest\x1a\x0f.sac.ModelState0\x01\x12.\n\x08GetModel\x12\x11.sac.ModelRequest\x1a\x0f.sac.ModelStateb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sac_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MODELSTATE"]._serialized_start = 18
    _globals["_MODELSTATE"]._serialized_end = 59
    _globals["_MODELREQUEST"]._serialized_start = 61
    _globals["_MODELREQUEST"]._serialized_end = 95
    _globals["_TENSORSERVICE"]._serialized_start = 97
    _globals["_TENSORSERVICE"]._serialized_end = 220
# @@protoc_insertion_point(module_scope)
