# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: async_inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "async_inference.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x61sync_inference.proto\x12\x0f\x61sync_inference"#\n\x13SelectActionRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"a\n\x19SelectActionStreamRequest\x12\x36\n\x0etransfer_state\x18\x01 \x01(\x0e\x32\x1e.async_inference.TransferState\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c"$\n\x14SelectActionResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"S\n\x0bObservation\x12\x36\n\x0etransfer_state\x18\x01 \x01(\x0e\x32\x1e.async_inference.TransferState\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c"N\n\x06\x41\x63tion\x12\x36\n\x0etransfer_state\x18\x01 \x01(\x0e\x32\x1e.async_inference.TransferState\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c"\x07\n\x05\x45mpty*`\n\rTransferState\x12\x14\n\x10TRANSFER_UNKNOWN\x10\x00\x12\x12\n\x0eTRANSFER_BEGIN\x10\x01\x12\x13\n\x0fTRANSFER_MIDDLE\x10\x02\x12\x10\n\x0cTRANSFER_END\x10\x03\x32\x9d\x03\n\x0e\x41syncInference\x12J\n\x10SendObservations\x12\x1c.async_inference.Observation\x1a\x16.async_inference.Empty(\x01\x12\x42\n\rStreamActions\x12\x16.async_inference.Empty\x1a\x17.async_inference.Action0\x01\x12\x37\n\x05Ready\x12\x16.async_inference.Empty\x1a\x16.async_inference.Empty\x12[\n\x0cSelectAction\x12$.async_inference.SelectActionRequest\x1a%.async_inference.SelectActionResponse\x12\x65\n\x12SelectActionStream\x12$.async_inference.SelectActionRequest\x1a%.async_inference.SelectActionResponse(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "async_inference_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TRANSFERSTATE"]._serialized_start = 390
    _globals["_TRANSFERSTATE"]._serialized_end = 486
    _globals["_SELECTACTIONREQUEST"]._serialized_start = 42
    _globals["_SELECTACTIONREQUEST"]._serialized_end = 77
    _globals["_SELECTACTIONSTREAMREQUEST"]._serialized_start = 79
    _globals["_SELECTACTIONSTREAMREQUEST"]._serialized_end = 176
    _globals["_SELECTACTIONRESPONSE"]._serialized_start = 178
    _globals["_SELECTACTIONRESPONSE"]._serialized_end = 214
    _globals["_OBSERVATION"]._serialized_start = 216
    _globals["_OBSERVATION"]._serialized_end = 299
    _globals["_ACTION"]._serialized_start = 301
    _globals["_ACTION"]._serialized_end = 379
    _globals["_EMPTY"]._serialized_start = 381
    _globals["_EMPTY"]._serialized_end = 388
    _globals["_ASYNCINFERENCE"]._serialized_start = 489
    _globals["_ASYNCINFERENCE"]._serialized_end = 902
# @@protoc_insertion_point(module_scope)
