import torch
import math


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        lower = norm_cdf((a - mean) / std)
        upper = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [lower, upper], then translate to
        # [2*lower-1, 2*upper-1].
        tensor.uniform_(2 * lower - 1, 2 * upper - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def eef_reconstruction_loss(
    s_pred: torch.Tensor,
    state_delta: torch.Tensor,
    state_mask: torch.Tensor,
    state_loss_type: str = "l1",
    reduction: str = "mean",
) -> torch.Tensor:
    if state_delta is None:
        raise ValueError("eef_reconstruction_loss requires `state_delta`.")
    if state_mask is None:
        raise ValueError("eef_reconstruction_loss requires `state_mask`.")

    pred_was_2d = s_pred.dim() == 2
    if s_pred.dim() == 2:
        s_pred = s_pred.unsqueeze(1)
    elif s_pred.dim() != 3:
        raise ValueError(f"s_pred must be [B,D] or [B,T,D], got {tuple(s_pred.shape)}")

    delta = state_delta
    if not torch.is_tensor(delta):
        delta = torch.as_tensor(delta, device=s_pred.device, dtype=s_pred.dtype)
    else:
        delta = delta.to(device=s_pred.device, dtype=s_pred.dtype)
    if delta.dim() == 2:
        delta = delta.unsqueeze(1)
    elif delta.dim() != 3:
        raise ValueError(f"state_delta must be [B,D] or [B,T,D], got {tuple(delta.shape)}")

    mask = state_mask
    if not torch.is_tensor(mask):
        mask = torch.as_tensor(mask, device=s_pred.device)
    else:
        mask = mask.to(device=s_pred.device)
    if mask.dim() == 2:
        mask = mask.unsqueeze(1)
    elif mask.dim() != 3:
        raise ValueError(f"state_mask must be [B,D] or [B,T,D], got {tuple(mask.shape)}")

    pred_t = int(s_pred.shape[1])
    if delta.shape[1] == 1 and pred_t > 1:
        delta = delta.expand(-1, pred_t, -1)
    elif delta.shape[1] != pred_t:
        raise ValueError(f"state_delta time dim mismatch: got {delta.shape[1]}, expected 1 or {pred_t}.")

    if mask.shape[1] == 1 and pred_t > 1:
        mask = mask.expand(-1, pred_t, -1)
    elif mask.shape[1] != pred_t:
        raise ValueError(f"state_mask time dim mismatch: got {mask.shape[1]}, expected 1 or {pred_t}.")

    if delta.shape[0] != s_pred.shape[0] or delta.shape[2] != s_pred.shape[2]:
        raise ValueError(
            f"state_delta shape mismatch: delta={tuple(delta.shape)} vs pred={tuple(s_pred.shape)}"
        )
    if mask.shape[0] != s_pred.shape[0] or mask.shape[2] != s_pred.shape[2]:
        raise ValueError(f"state_mask shape mismatch: mask={tuple(mask.shape)} vs pred={tuple(s_pred.shape)}")

    if state_loss_type == "l1":
        raw_loss = torch.abs(s_pred - delta)
    elif state_loss_type == "l2":
        raw_loss = (s_pred - delta) ** 2
    else:
        raise ValueError(f"Unsupported state_loss_type: {state_loss_type}")

    mask_f = mask.to(dtype=raw_loss.dtype)
    masked_loss = raw_loss * mask_f

    if reduction == "mean":
        valid_count = mask_f.sum().clamp_min(1.0)
        out = masked_loss.sum() / valid_count
    elif reduction == "sum":
        out = masked_loss.sum()
    elif reduction == "none":
        out = masked_loss
        if pred_was_2d:
            out = out.squeeze(1)
    else:
        raise ValueError(f"Unsupported reduction: {reduction}")

    return out


def charbonnier_loss(input: torch.Tensor, target: torch.Tensor, eps: float = 0.1) -> torch.Tensor:
    diff = input - target
    return torch.mean(torch.sqrt(diff * diff + eps * eps))
