# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
python -m lerobot.record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example with bilateral teleoperation:

```shell
python -m lerobot.record \
    --robot.type=so101_follower_t \
    --robot.port=/dev/tty.usbmodem58760432961 \
    --robot.id=follower_arm_torque \
    --dataset.repo_id=pepijn/bilateral-teleop-test \
    --dataset.num_episodes=5 \
    --dataset.single_task="Wipe the table" \
    --biteleop=true \
    --teleop.type=so101_follower_t \
    --teleop.port=/dev/tty.usbmodem58760432571 \
    --teleop.id=leader_arm_torque \
    --dataset.fps=100 \
    --robot.cameras="{side: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 100}}" \
    --display_data=true
```

Example Eval with bilateral teleoperation:
```
python -m lerobot.record  \
  --robot.type=so101_follower_t \
  --robot.port=/dev/tty.usbmodem58760432961 \
  --robot.id=follower_arm_torque \
  --robot.cameras="{side: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 100}}" \
  --display_data=true \
  --dataset.repo_id=pepijn223/eval_bilateral-wipe-large \
  --dataset.single_task="Wipe the table" \
  --policy.path=pepijn223/bilateral-wipe-large-single \
  --dataset.fps=100 \
  --biteleop=true
```

"""

import logging
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat
from typing import List

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.policies.factory import make_policy
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
    so101_follower_torque,
)
from lerobot.robots.so101_follower_torque import SO101FollowerT
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import _init_rerun, log_rerun_data


def split_interleaved_action(vec, motors):
    """
    vec     : 1‑D tensor/array, length = 3*len(motors)
    motors  : ['shoulder_pan', 'shoulder_lift', …]

    returns : pos, vel, tau  (three dicts keyed by joint name)
    """
    pos = {}
    vel = {}
    tau = {}
    for i, j in enumerate(motors):
        base = 3 * i
        pos[j] = float(vec[base + 0])
        vel[j] = float(vec[base + 1])
        tau[j] = float(vec[base + 2])
    return pos, vel, tau


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | RobotConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # Enable bilateral teleoperation with force feedback
    biteleop: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator
    | List[Teleoperator]
    | Robot
    | None = None,  # Allow Robot type for bilateral teleoperation
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    biteleop: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    # Check if bilateral teleoperation is enabled and validate robot/teleop types
    if biteleop and policy is None:
        if not isinstance(robot, SO101FollowerT):
            raise ValueError(
                "Bilateral teleoperation requires both robot and teleop to be of type SO101FollowerT"
            )
        logging.info("Bilateral teleoperation mode enabled")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(t, (so100_leader.SO100Leader, so101_leader.SO101Leader, koch_leader.KochLeader))
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # if policy is given it needs cleaning up
    if policy is not None:
        policy.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()

    # For controlling rerun logging frequency
    loop_count = 0
    rerun_log_freq = max(1, int(fps / 10))  # Log at 10Hz

    while control_time_s is not None and timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        observation = robot.get_observation()

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")

        if (
            biteleop
            and isinstance(robot, SO101FollowerT)
            and isinstance(teleop, SO101FollowerT)
            and policy is None
        ):
            # Get observations from both arms
            obs_f = observation  # robot is the follower
            obs_l = teleop.get_observation()

            # Collect data for all motors
            pos_f = {j: obs_f[f"{j}.pos"] for j in robot.bus.motors}
            vel_f = {j: obs_f[f"{j}.vel"] for j in robot.bus.motors}
            tau_reaction_f = {j: obs_f[f"{j}.effort"] for j in robot.bus.motors}

            pos_l = {j: obs_l[f"{j}.pos"] for j in teleop.bus.motors}
            vel_l = {j: obs_l[f"{j}.vel"] for j in teleop.bus.motors}
            acc_l = {j: obs_l[f"{j}.acc"] for j in teleop.bus.motors}
            tau_reaction_l = {j: obs_l[f"{j}.effort"] for j in teleop.bus.motors}

            # Get control gains from robot
            kp_gains = robot.kp_gains
            kd_gains = robot.kd_gains
            kf_gains = robot.kf_gains

            # Compute torque commands in one line using list comprehension
            tau_cmd_f = [
                (
                    kp_gains[j] * (pos_l[j] - pos_f[j])  # Position tracking
                    + kd_gains[j] * (vel_l[j] - vel_f[j])  # Velocity damping
                    + kf_gains[j] * (-tau_reaction_l[j] - tau_reaction_f[j])
                )  # Force reflection
                for j in robot.bus.motors
            ]

            tau_cmd_l = [
                (
                    kp_gains[j] * (pos_f[j] - pos_l[j])  # Position tracking
                    + kd_gains[j] * (vel_f[j] - vel_l[j])  # Velocity damping
                    + kf_gains[j] * (-tau_reaction_f[j] - tau_reaction_l[j])
                )  # Force reflection
                for j in teleop.bus.motors
            ]

            # Send torque commands
            action = {f"{m}.effort": tau_cmd_f[i] for i, m in enumerate(robot.bus.motors)}
            teleop_action = {f"{m}.effort": tau_cmd_l[i] for i, m in enumerate(teleop.bus.motors)}
            teleop.send_action(teleop_action)
            robot.send_action(action)

            # For bilateral teleoperation, create custom observation and action for dataset
            bilateral_action = {}
            for j in teleop.bus.motors:
                bilateral_action[f"{j}.pos"] = pos_l[j]
                bilateral_action[f"{j}.vel"] = vel_l[j]
                bilateral_action[f"{j}.acc"] = acc_l[j]
                bilateral_action[f"{j}.effort"] = -tau_reaction_l[j]

            # Override the observation_frame and action for dataset recording
            if dataset is not None:
                observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")
                # Store bilateral_action to be used later when building action_frame
                action = bilateral_action

        elif policy is not None and biteleop and isinstance(robot, SO101FollowerT):
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            # Read robot current state
            pos_f = {j: observation[f"{j}.pos"] for j in robot.bus.motors}
            vel_f = {j: observation[f"{j}.vel"] for j in robot.bus.motors}
            tau_reaction_f = {j: observation[f"{j}.effort"] for j in robot.bus.motors}

            # The model returns [pos1, pos2, …, vel1, vel2, …, tau1, tau2, …]
            motors = robot.bus.motors  # 6 joints in your case
            pos_l, vel_l, neg_tau_reaction_l = split_interleaved_action(
                action_values, motors
            )  # The model is trained and returns the effort already as negative: -tau_reaction_l

            # Get control gains from the robot instance
            kp, kd, kf = robot.kp_gains, robot.kd_gains, robot.kf_gains

            # Compute torque command for the follower robot
            tau_cmd_f = [
                (
                    kp[j] * (pos_l[j] - pos_f[j])  # Position tracking
                    + kd[j] * (vel_l[j] - vel_f[j])  # Velocity damping
                    + kf[j] * (neg_tau_reaction_l[j] - tau_reaction_f[j])  # Force reflection
                )
                for j in robot.bus.motors
            ]

            # Format action with calculated torques and send to robot
            action = {f"{m}.effort": tau_cmd_f[i] for i, m in enumerate(robot.bus.motors)}
            robot.send_action(action)

            bilateral_action = {}
            for j in robot.bus.motors:
                bilateral_action[f"{j}.pos"] = pos_l[j]
                bilateral_action[f"{j}.vel"] = vel_l[j]
                bilateral_action[f"{j}.effort"] = neg_tau_reaction_l[j]

            # Override the observation_frame and action for dataset recording
            if dataset is not None:
                observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")
                # Store bilateral_action to be used later when building action_frame
                action = bilateral_action

        elif policy is not None and not biteleop:
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            action = {key: action_values[i].item() for i, key in enumerate(robot.action_features)}
        elif policy is None and isinstance(teleop, Teleoperator) and not biteleop:
            action = teleop.get_action()
        elif policy is None and isinstance(teleop, list) and not biteleop:
            # TODO(pepijn, steven): clean the record loop for use of multiple robots (possibly with pipeline)
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}

            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)

            action = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset.
        if not biteleop:
            sent_action = robot.send_action(action)

        if dataset is not None:
            # For bilateral teleoperation, use the bilateral_action (leader pos & torque)
            # For other modes, use sent_action as usual
            if biteleop and isinstance(robot, SO101FollowerT):
                action_frame = build_dataset_frame(dataset.features, action, prefix="action")
            else:
                action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}
            dataset.add_frame(frame, task=single_task)

        if display_data and loop_count % rerun_log_freq == 0:
            log_rerun_data(observation, action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t
        loop_count += 1


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))

    if cfg.display_data:
        _init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)

    # For bilateral teleoperation, create teleop as a robot instance
    if cfg.biteleop and cfg.teleop is not None:
        print("Bilateral teleoperation enabled")
        # For bilateral teleoperation, both arms must be SO101FollowerT robots
        from lerobot.robots.so101_follower_torque.config_so101_follower_t import SO101FollowerTConfig

        # Check if teleop config has the right type
        if cfg.teleop.type != "so101_follower_t":
            raise ValueError("Bilateral teleoperation requires teleop.type to be 'so101_follower_t'")

        # Create teleop as SO101FollowerT robot instance
        # Access attributes dynamically since they vary by teleop config type
        port = getattr(cfg.teleop, "port", None)
        if port is None:
            raise ValueError("Bilateral teleoperation requires teleop.port to be specified")

        teleop_robot_config = SO101FollowerTConfig(
            port=port,
            id=getattr(cfg.teleop, "id", "leader_arm_torque"),
            cameras=getattr(cfg.teleop, "cameras", {}),
            disable_torque_on_disconnect=getattr(cfg.teleop, "disable_torque_on_disconnect", True),
        )

        teleop = SO101FollowerT(teleop_robot_config)
    else:
        teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)
    dataset_features = {**action_features, **obs_features}

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
        )

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    recorded_episodes = 0
    while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
        log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
        record_loop(
            robot=robot,
            events=events,
            fps=cfg.dataset.fps,
            teleop=teleop,
            policy=policy,
            dataset=dataset,
            control_time_s=cfg.dataset.episode_time_s,
            single_task=cfg.dataset.single_task,
            display_data=cfg.display_data,
            biteleop=cfg.biteleop,
        )

        # Execute a few seconds without recording to give time to manually reset the environment
        # Skip reset for the last episode to be recorded
        if not events["stop_recording"] and (
            (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
        ):
            log_say("Reset the environment", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop=teleop,
                control_time_s=cfg.dataset.reset_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
                biteleop=cfg.biteleop,
            )

        if events["rerecord_episode"]:
            log_say("Re-record episode", cfg.play_sounds)
            events["rerecord_episode"] = False
            events["exit_early"] = False
            dataset.clear_episode_buffer()
            continue

        dataset.save_episode()
        recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


if __name__ == "__main__":
    record()
