# Copyright 2026 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Inference steps for the SmolVLA2 multi-rate runtime.

Each step is a tiny class with a ``trigger`` and an ``__call__(state)``;
the runtime applies them in order each tick. When a step's trigger
doesn't fire, the step is a no-op and the runtime moves on.

Stream-to-step mapping mirrors the ``subtasks_vqa.yaml`` recipe:

* ``LowLevelForward``        — calls ``policy.select_action`` for the
                                action chunk; trained by
                                ``low_level_execution``
* ``EnqueueChunk``           — pushes the chunk to ``action_queue``
* ``DispatchAction``         — pops one action per control tick and
                                forwards to the robot
* ``HighLevelSubtaskFwd``    — calls ``policy.select_message`` for the
                                next subtask; trained by
                                ``high_level_subtask``
* ``MemoryUpdateFwd``        — fires on subtask boundary; trained by
                                ``memory_update``
* ``UserInterjectionFwd``    — fires on stdin interjection; trained by
                                ``user_interjection_response``
* ``AskVQAFwd``              — fires on stdin question; trained by
                                ``ask_vqa_*``
* ``DispatchToolCalls``      — pops ``tool_calls_pending`` and calls
                                the matching ``Tool`` instance
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any

from .runtime_state import push_log, set_if_changed, take_event
from .triggers import EventTrigger, HzTrigger, Trigger

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Step base + runner
# ---------------------------------------------------------------------------


@dataclass
class InferenceStep:
    """A trigger-gated callable. Subclasses override :meth:`run`."""

    trigger: Trigger

    def __call__(self, state: dict[str, Any]) -> dict[str, Any]:
        if not self.trigger.should_fire(state["_tick"], state):
            return state
        return self.run(state) or state

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:  # pragma: no cover
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Low-level (action) path
# ---------------------------------------------------------------------------


@dataclass
class LowLevelForward(InferenceStep):
    """Run the policy's action head and produce one action chunk."""

    policy: Any = None
    observation_provider: Any = None
    """Callable ``() -> dict``: returns the current observation batch
    (already preprocessed). Typically wraps the robot's camera /
    proprio reads. ``None`` in dry-run mode → step skips."""

    trigger: Trigger = field(default_factory=lambda: HzTrigger(hz=4.0))

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:
        if self.policy is None or self.observation_provider is None:
            return None
        # ``/vlm`` mode pauses the whole action loop so the robot holds
        # position while the operator probes the VLM with VQA.
        if state.get("mode", "action") != "action":
            return None
        if not state.get("task"):
            return None

        # SmolVLA produces *action chunks* (typically 50 steps via
        # flow-matching). Every step gets dispatched to the robot;
        # popping one per dispatch tick is essentially free. Only
        # generate a new chunk once the previous one has fully
        # drained — this is the canonical "sense → think → act"
        # loop. Refreshing while a chunk is still queued causes the
        # new chunk to "telescope" past the old one (planned from an
        # observation that's already 25+ steps stale by the time it
        # starts dispatching).
        queue = state.setdefault("action_queue", [])
        if len(queue) > 0:
            return None

        observation = self.observation_provider()
        if observation is None:
            return None

        # The action expert is conditioned on the SUBTASK generated by
        # the high-level loop (``HighLevelSubtaskFwd`` runs earlier in
        # the pipeline and writes ``current_subtask``). Matches the
        # training-time ``low_level_execution`` recipe — ``user(${subtask})``.
        # Falls back to the task string only on the very first frame,
        # before the high-level loop has produced a subtask.
        subtask = state.get("current_subtask") or state.get("task") or ""
        ctx = [{"role": "user", "content": subtask}]
        # ``add_generation_prompt=False`` to match the training-time
        # prefix shape: at training the action expert sees the rendered
        # user turn ending at ``<|im_end|>`` (no trailing
        # ``<|im_start|>assistant\n``). Passing True here would append
        # extra role-marker tokens the action expert never saw during
        # training.
        text_batch = _build_text_batch(self.policy, ctx, add_generation_prompt=False)
        from lerobot.utils.constants import (  # noqa: PLC0415
            OBS_LANGUAGE_ATTENTION_MASK,
            OBS_LANGUAGE_TOKENS,
        )

        observation = dict(observation)
        observation[OBS_LANGUAGE_TOKENS] = text_batch["lang_tokens"]
        observation[OBS_LANGUAGE_ATTENTION_MASK] = text_batch["lang_masks"]

        try:
            # ``predict_action_chunk`` returns the *full* chunk shape
            # ``(batch, n_action_steps, action_dim)``. Enqueue every
            # step so DispatchAction at ctrl_hz can drain them
            # smoothly until the next refresh.
            chunk = self.policy.predict_action_chunk(observation)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "predict_action_chunk failed: %s",
                exc,
                exc_info=logger.isEnabledFor(logging.DEBUG),
            )
            push_log(
                state,
                f"  [warn] predict_action_chunk failed: "
                f"{type(exc).__name__}: {exc}",
            )
            return None

        # ``chunk`` shape: ``(batch, n_action_steps, action_dim)``. Push
        # each step as a ``(1, action_dim)`` tensor so the existing
        # action executor's batch-squeeze logic works unchanged.
        if chunk.ndim == 3:
            chunk_iter = chunk[0]  # ``(n_action_steps, action_dim)``
        elif chunk.ndim == 2:
            chunk_iter = chunk
        else:
            chunk_iter = chunk.unsqueeze(0)
        for step in chunk_iter:
            queue.append(step.unsqueeze(0))
        state["last_chunk_size"] = int(chunk_iter.shape[0])
        return None


@dataclass
class DispatchAction(InferenceStep):
    """Pop one action per tick and hand it to the robot.

    In dry-run mode (``robot_executor=None``) the step still pops the
    queue so it doesn't grow unbounded — the popped tensor is logged
    instead of executed.

    Wall-clock catch-up: the action queue represents an open-loop
    trajectory at a fixed step rate (``trigger.hz`` ≈ ``ctrl_hz``).
    When the main loop stalls — e.g. an LLM call for the high-level
    subtask blocks for ~2 s on MPS — the dispatch trigger fires only
    once over that whole interval. Naively popping a single entry per
    fire makes the robot lag further and further behind the planned
    timeline, and a 50-step chunk would take ~125 s to drain instead
    of ~1.7 s. Track real elapsed time between dispatches and pop
    ``round(elapsed * hz)`` entries, sending the most recent one. The
    skipped intermediate joint targets are stale anyway — the dynamixel
    will smooth toward the latest goal position.
    """

    robot_executor: Any = None
    trigger: Trigger = field(default_factory=lambda: HzTrigger(hz=50.0))
    _last_dispatch_t: float | None = field(default=None, init=False)

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:
        import time as _time  # noqa: PLC0415

        # ``/vlm`` mode pauses dispatch — the robot holds its last
        # commanded position while the operator runs VQA.
        if state.get("mode", "action") != "action":
            self._last_dispatch_t = None
            return None

        queue = state.get("action_queue")
        if not queue:
            # Reset wall-clock anchor when the queue is empty so the
            # next chunk doesn't see a huge fake "elapsed" window.
            self._last_dispatch_t = None
            return None

        now = _time.monotonic()
        hz = getattr(self.trigger, "hz", 30.0)
        if self._last_dispatch_t is None or hz <= 0:
            n_to_pop = 1
        else:
            elapsed = now - self._last_dispatch_t
            # ``max(1, ...)`` so we always pop at least one when the
            # trigger fires; ``min(len(queue), ...)`` so we don't run
            # off the end of the chunk.
            n_to_pop = max(1, min(len(queue), int(round(elapsed * hz))))
        self._last_dispatch_t = now

        # Drain ``n_to_pop`` stale entries, keep only the latest as the
        # action actually sent. The intermediate joint targets would
        # all be ~10–30 ms apart in chunk time — the robot can't track
        # them individually anyway when the host loop is slow.
        latest = None
        for _ in range(n_to_pop):
            if not queue:
                break
            latest = queue.popleft() if hasattr(queue, "popleft") else queue.pop(0)
            state["actions_dispatched"] = state.get("actions_dispatched", 0) + 1

        if latest is not None and self.robot_executor is not None:
            self.robot_executor(latest)
        return None


# ---------------------------------------------------------------------------
# High-level (text) paths — all use policy.select_message
# ---------------------------------------------------------------------------


def _build_text_batch(
    policy: Any,
    prompt_messages: list[dict[str, Any]],
    *,
    add_generation_prompt: bool = True,
) -> dict[str, Any]:
    """Tokenize chat messages into the batch ``select_message`` expects.

    Dispatches on the policy backbone so one runtime drives both:

    * ``smolvla2`` (SmolVLM2) — chat template via ``apply_chat_template``.
    * ``pi052`` (PaliGemma) — flat ``Role: content`` text, since
      PaliGemma is not chat-pretrained (mirrors ``PI052TextTokenizerStep``).
    """
    if getattr(getattr(policy, "config", None), "type", "") == "pi052":
        return _build_text_batch_pi052(
            policy, prompt_messages, add_generation_prompt=add_generation_prompt
        )
    return _build_text_batch_chat(
        policy, prompt_messages, add_generation_prompt=add_generation_prompt
    )


def _build_text_batch_pi052(
    policy: Any,
    prompt_messages: list[dict[str, Any]],
    *,
    add_generation_prompt: bool = True,
) -> dict[str, Any]:
    """PI052 text batch — flat ``User: … \\nAssistant: …`` prompt.

    PaliGemma ships no chat template, so PI052 trains on the plain
    role-prefixed concatenation built by ``PI052TextTokenizerStep``.
    Reuses that exact formatter so the inference prefix matches
    training. ``add_generation_prompt`` appends the bare ``Assistant: ``
    header the LM head continues from.
    """
    import torch  # noqa: PLC0415
    from transformers import AutoTokenizer  # noqa: PLC0415

    from lerobot.policies.pi052.text_processor_pi052 import (  # noqa: PLC0415
        _flatten_say_tool_calls,
        _format_messages,
        _strip_blocks,
        register_paligemma_loc_tokens,
    )

    tok_name = (
        getattr(policy.config, "tokenizer_name", None) or "google/paligemma-3b-pt-224"
    )
    # Register PaliGemma's <locDDDD> tokens so inference encoding /
    # decoding sees them as single vocab ids — must match training.
    tokenizer = register_paligemma_loc_tokens(AutoTokenizer.from_pretrained(tok_name))

    messages = [_strip_blocks(_flatten_say_tool_calls(m)) for m in prompt_messages]
    prompt, _spans = _format_messages(messages)
    if add_generation_prompt:
        prompt = prompt + "Assistant: "

    encoded = tokenizer(prompt, return_tensors="pt")
    ids = encoded["input_ids"]
    attn = encoded.get("attention_mask")
    if attn is None and tokenizer.pad_token_id is not None:
        attn = ids != tokenizer.pad_token_id
    if attn is not None and hasattr(attn, "dtype") and attn.dtype != torch.bool:
        attn = attn.bool()

    device = getattr(getattr(policy, "config", None), "device", None)
    if device is not None:
        try:
            ids = ids.to(device)
            if attn is not None and hasattr(attn, "to"):
                attn = attn.to(device)
        except Exception as exc:  # noqa: BLE001
            logger.debug("could not move pi052 lang tokens to %s: %s", device, exc)
    return {"lang_tokens": ids, "lang_masks": attn, "tokenizer": tokenizer}


def _build_text_batch_chat(
    policy: Any,
    prompt_messages: list[dict[str, Any]],
    *,
    add_generation_prompt: bool = True,
) -> dict[str, Any]:
    """SmolVLA2 (SmolVLM2) text batch — chat-template tokenization.

    Reuses ``_strip_lerobot_blocks`` so the inference prompt shape
    matches the training-time chat tokenizer step exactly.
    """
    from transformers import AutoTokenizer  # noqa: PLC0415

    tokenizer = AutoTokenizer.from_pretrained(policy.config.vlm_model_name)
    if tokenizer.pad_token_id is None and tokenizer.eos_token_id is not None:
        tokenizer.pad_token = tokenizer.eos_token

    # Reuse the *exact* normaliser that the training-time chat
    # tokenizer step uses (``_strip_lerobot_blocks``). It handles all
    # the cases the SmolVLM chat template expects:
    #   * ``content: list[block]`` → keep text blocks, drop images
    #   * ``content: None`` → ``[{type: text, text: ""}]``
    #   * ``content: str`` / anything else → ``[{type: text, text: str(content)}]``
    # Doing it any other way creates a training/inference mismatch in
    # exactly the prompt shape the model was supervised on. Also
    # strips ``stream`` / ``target`` recipe metadata.
    from lerobot.policies.smolvla2.chat_processor_smolvla2 import (  # noqa: PLC0415
        _strip_lerobot_blocks,
    )

    text_messages = [_strip_lerobot_blocks(m) for m in prompt_messages]
    encoded = tokenizer.apply_chat_template(
        text_messages,
        add_generation_prompt=add_generation_prompt,
        tokenize=True,
        return_tensors="pt",
    )
    # ``apply_chat_template`` can return any of:
    #   - a Tensor of shape ``(seq,)`` or ``(1, seq)`` (older transformers),
    #   - a list[int] / list[list[int]] (when ``return_tensors`` is ignored),
    #   - a ``BatchEncoding`` dict-like with ``input_ids`` / ``attention_mask``
    #     (newer transformers, especially via processor.apply_chat_template
    #     forwarding through here).
    # Normalise to ``ids: Tensor[1, seq]`` and grab the encoder's
    # attention mask when available so we don't have to re-derive it
    # from ``pad_token_id`` (which can be ``None`` for SmolVLM).
    attn: Any = None
    if hasattr(encoded, "input_ids"):
        ids = encoded.input_ids
        attn = getattr(encoded, "attention_mask", None)
    elif isinstance(encoded, dict) and "input_ids" in encoded:
        ids = encoded["input_ids"]
        attn = encoded.get("attention_mask")
    else:
        ids = encoded
    if isinstance(ids, list):
        if ids and isinstance(ids[0], list):
            ids = ids[0]
        import torch  # noqa: PLC0415

        ids = torch.tensor(ids, dtype=torch.long)
    if hasattr(ids, "ndim") and ids.ndim == 1:
        ids = ids.unsqueeze(0)
    if attn is None and tokenizer.pad_token_id is not None:
        attn = ids != tokenizer.pad_token_id
    elif isinstance(attn, list):
        import torch  # noqa: PLC0415

        attn = torch.tensor(attn, dtype=torch.long)
        if attn.ndim == 1:
            attn = attn.unsqueeze(0)
    # SmolVLA's ``eager_attention_forward`` does
    # ``torch.where(attention_mask[..., None, :, :], ...)`` which
    # requires a *bool* condition tensor; ``BatchEncoding``'s
    # attention_mask is typically Long (0/1). Cast so the prefix
    # forward doesn't blow up with ``where expected condition to be a
    # boolean tensor, but got a tensor with dtype Long``.
    if attn is not None and hasattr(attn, "dtype"):
        import torch as _torch  # noqa: PLC0415

        if attn.dtype != _torch.bool:
            attn = attn.bool()
    # Move tokens onto the policy's device — otherwise prefix embedding
    # raises a device-mismatch on every forward (CPU tensor vs MPS / CUDA
    # model), which the caller's broad except would swallow silently.
    device = getattr(getattr(policy, "config", None), "device", None)
    if device is not None:
        try:
            ids = ids.to(device)
            if attn is not None and hasattr(attn, "to"):
                attn = attn.to(device)
        except Exception as exc:  # noqa: BLE001
            logger.debug("could not move lang tokens to %s: %s", device, exc)
    return {"lang_tokens": ids, "lang_masks": attn, "tokenizer": tokenizer}


def _strip_recipe_keys(m: dict[str, Any]) -> dict[str, Any]:
    new = dict(m)
    new.pop("stream", None)
    new.pop("target", None)
    return new


@dataclass
class HighLevelSubtaskFwd(InferenceStep):
    """At ~1 Hz, ask the policy for the next subtask.

    Mirrors the ``high_level_subtask`` recipe layout exactly:

        user:   "${task}\\nPlan: ${plan}\\nMemory: ${memory}"
        user:   "Current subtask: ${subtask}"        (if subtask present)
        ↓ generate ↓
        assistant: <next subtask>
    """

    policy: Any = None
    observation_provider: Any = None
    """Same shape as ``LowLevelForward.observation_provider``. When
    set, the resulting observation is merged into ``select_message``'s
    batch so text generation runs against real video + state."""

    trigger: Trigger = field(default_factory=lambda: HzTrigger(hz=1.0))

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:
        if self.policy is None or not state.get("task"):
            return None
        # ``/vlm`` mode pauses subtask generation along with the rest of
        # the action loop.
        if state.get("mode", "action") != "action":
            return None
        # Gate to chunk boundaries: only generate a fresh subtask when
        # the action queue is empty (i.e. right before LowLevelForward
        # refreshes the chunk). ``select_message`` takes ~2 s on MPS,
        # and running it every loop iteration starves DispatchAction
        # at ctrl_hz=30 — the queue drains at ~0.4 actions/sec instead
        # of 30/sec and the robot barely moves. Tying it to the same
        # "queue empty" condition as the chunk refresh produces a
        # clean sense → think → act cycle.
        queue = state.get("action_queue") or []
        if len(queue) > 0:
            return None
        ctx = _msgs_for_subtask(state)
        observation = _maybe_observation(self.observation_provider)
        # Default: greedy argmax, no min_new_tokens, no special-token
        # suppression — matches training. Operator can override via
        # ``--text_min_new_tokens=N --text_temperature=T --text_top_p=P``
        # on the CLI; useful for under-trained checkpoints whose LM
        # head still favours EOS at position 0 (pre-trained chat
        # backbone's short-turn prior hasn't been fully overridden
        # by the fine-tuning supervision yet).
        msg = _generate_with_policy(
            self.policy,
            ctx,
            observation=observation,
            state=state,
            label="subtask gen",
            min_new_tokens=int(state.get("text_gen_min_new_tokens") or 0),
            temperature=float(state.get("text_gen_temperature") or 0.0),
            top_p=float(state.get("text_gen_top_p") or 1.0),
            # Subtasks never legitimately contain PaliGemma ``<loc>``
            # tokens — suppress them so a checkpoint whose LM head
            # has drifted toward the pretrained loc-prior falls back
            # to its (still-correct) text mass.
            suppress_loc_tokens=True,
        )
        # Diagnostics: surface what the model is *actually* producing
        # at chunk boundaries, even when the output gets rejected or
        # repeats. Memorisation collapse looks like "same accepted
        # subtask N times in a row" or "gibberish_count rising while
        # current_subtask is stuck". The state panel renders these.
        state["last_subtask_raw"] = msg or ""
        # Persistent empty completion is its own failure mode (model
        # immediately EOS-es from the chat-template generation
        # prompt) — surface it once every N occurrences so the
        # operator can distinguish "generation failing silently"
        # from "generating fine but filter rejecting".
        if not msg:
            empties = state.get("subtask_empty_count", 0) + 1
            state["subtask_empty_count"] = empties
            if empties == 1 or empties % 5 == 0:
                debug = getattr(self.policy, "_last_select_message_debug", "") or ""
                if debug:
                    push_log(
                        state,
                        f"  [info] subtask gen empty (×{empties}); {debug}",
                    )
                else:
                    push_log(
                        state,
                        f"  [info] subtask gen returned empty (×{empties}) — "
                        "no tokens generated (head EOS-ing before any "
                        "non-special token).",
                    )
        if msg and _looks_like_gibberish(msg):
            # Bump a counter so the operator can see the model is
            # struggling without spamming the log every tick. A first
            # rejection still logs once so the failure is visible.
            count = state.get("subtask_gibberish_count", 0) + 1
            state["subtask_gibberish_count"] = count
            if count == 1 or count % 30 == 0:
                push_log(
                    state,
                    f"  [info] subtask gen rejected (gibberish ×{count}): {msg[:60]!r}",
                )
            return None
        if msg:
            prev_subtask = state.get("current_subtask")
            changed = set_if_changed(state, "current_subtask", msg, label="subtask")
            if changed:
                # Stash the just-completed subtask so ``MemoryUpdateFwd``
                # can drop it into its prompt as ``Completed subtask:``
                # — the recipe binds ``completed_subtask`` to
                # ``nth_prev(style=subtask, offset=1)``, i.e. the subtask
                # that was active *before* the change.
                if prev_subtask:
                    state["prior_subtask"] = prev_subtask
                # Subtask change is a downstream trigger.
                state.setdefault("events_this_tick", []).append("subtask_change")
                state["subtask_repeat_count"] = 0
            else:
                # Same accepted string regenerated — memorisation tell.
                # Once this counter climbs past a few, you're seeing
                # the model unable to move past the current subtask
                # despite the chunk having drained (visual scene may
                # have changed but the LM is replaying training
                # tokens).
                state["subtask_repeat_count"] = (
                    state.get("subtask_repeat_count", 0) + 1
                )
        # Silently skip empty completions — common when the model
        # warms up or generates only EOS; logging it every tick at
        # ctrl_hz is just noise.
        return None


@dataclass
class MemoryUpdateFwd(InferenceStep):
    """On subtask boundary, refresh the compressed memory.

    Mirrors the ``memory_update`` recipe layout exactly:

        user:      "${task}"
        assistant: "Previous memory: ${prior_memory}"   (if prior memory)
        user:      "Completed subtask: ${completed_subtask}"  (if subtask)
        ↓ generate ↓
        assistant: <new memory>
    """

    policy: Any = None
    observation_provider: Any = None
    trigger: Trigger = field(default_factory=lambda: EventTrigger("subtask_change"))

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:
        # Don't consume the event — multiple steps may want to react.
        if self.policy is None:
            return None
        ctx = _msgs_for_memory(state)
        observation = _maybe_observation(self.observation_provider)
        new_memory = _generate_with_policy(
            self.policy,
            ctx,
            observation=observation,
            state=state,
            label="memory gen",
            suppress_loc_tokens=True,
        )
        state["last_memory_raw"] = new_memory or ""
        if new_memory and _looks_like_gibberish(new_memory):
            count = state.get("memory_gibberish_count", 0) + 1
            state["memory_gibberish_count"] = count
            push_log(
                state,
                f"  [info] memory gen rejected (gibberish ×{count}): {new_memory[:60]!r}",
            )
            return None
        if new_memory:
            set_if_changed(state, "current_memory", new_memory, label="memory")
        return None


@dataclass
class UserInterjectionFwd(InferenceStep):
    """On stdin interjection, refresh the plan + emit a paired ``say``.

    Mirrors the ``user_interjection_response`` recipe layout exactly:

        user:      "${task}"
        assistant: "Previous plan:\\n${prior_plan}"   (if prior plan)
        user:      "${interjection}"                  (the new utterance)
        ↓ generate ↓
        assistant: <plan + <say>...</say>>
    """

    policy: Any = None
    observation_provider: Any = None
    trigger: Trigger = field(default_factory=lambda: EventTrigger("user_interjection"))

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:
        if self.policy is None or not take_event(state, "user_interjection"):
            return None
        ctx = _msgs_for_interjection(state)
        observation = _maybe_observation(self.observation_provider)
        out = _generate_with_policy(
            self.policy,
            ctx,
            observation=observation,
            state=state,
            label="plan/say gen",
            suppress_loc_tokens=True,
        )
        if not out:
            # Don't log every empty completion — happens repeatedly on
            # MPS during warm-up and floods the panel. The user can
            # re-trigger by typing again.
            return None
        if _looks_like_gibberish(out):
            count = state.get("plan_gibberish_count", 0) + 1
            state["plan_gibberish_count"] = count
            push_log(
                state,
                f"  [info] plan/say gen rejected (gibberish ×{count}): {out[:60]!r}",
            )
            return None
        # Heuristic split: model is trained to emit one assistant turn
        # carrying both plan text AND a `say` tool call. Look for a
        # "<say>...</say>" or "say(...)" marker; fall back to whole
        # text → plan, no speech.
        plan_text, speech_text = _split_plan_and_say(out)
        if plan_text and _looks_like_gibberish(plan_text):
            plan_text = ""
        if plan_text:
            set_if_changed(state, "current_plan", plan_text, label="plan")
        if speech_text:
            push_log(state, f"  speech: {speech_text}")
            state.setdefault("tool_calls_pending", []).append(
                {
                    "type": "function",
                    "function": {"name": "say", "arguments": {"text": speech_text}},
                }
            )
            state.setdefault("events_this_tick", []).append("tool_call_pending")
        # Mark interjection consumed.
        state["recent_interjection"] = None
        return None


@dataclass
class AskVQAFwd(InferenceStep):
    """On stdin question, answer a frame-grounded VQA.

    Mirrors the ``ask_vqa_*`` recipe layout exactly: a single user
    turn carrying just the VQA question, plus the camera image block
    in training (we drop the image at inference because the dataset's
    image preprocessing doesn't match SmolVLM's vision tower input).

        user:   <question>
        ↓ generate ↓
        assistant: <vqa answer>
    """

    policy: Any = None
    observation_provider: Any = None
    trigger: Trigger = field(default_factory=lambda: EventTrigger("user_vqa_query"))

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:
        if self.policy is None or not take_event(state, "user_vqa_query"):
            return None
        question = state.get("recent_vqa_query")
        if not question:
            return None
        ctx = _msgs_for_vqa(question)
        observation = _maybe_observation(self.observation_provider)
        answer = _generate_with_policy(
            self.policy,
            ctx,
            observation=observation,
            state=state,
            label="vqa gen",
        )
        # VQA answers are intentionally JSON-like during training, so
        # ``_looks_like_gibberish`` would false-positive on them. Keep
        # the answer as-is — the VQA panel line lets the user judge.
        if answer:
            push_log(state, f"  vqa: {answer}")
        state["recent_vqa_query"] = None
        return None


# ---------------------------------------------------------------------------
# Tool dispatch
# ---------------------------------------------------------------------------


@dataclass
class DispatchToolCalls(InferenceStep):
    """Pop ``tool_calls_pending`` and execute them via :data:`TOOL_REGISTRY`."""

    tools: dict[str, Any] = field(default_factory=dict)
    trigger: Trigger = field(default_factory=lambda: EventTrigger("tool_call_pending"))

    def run(self, state: dict[str, Any]) -> dict[str, Any] | None:
        take_event(state, "tool_call_pending")
        pending = state.get("tool_calls_pending") or []
        for call in pending:
            try:
                fn = (call or {}).get("function") or {}
                name = fn.get("name")
                args = fn.get("arguments") or {}
                tool = self.tools.get(name)
                if tool is None:
                    push_log(state, f"  [warn] tool {name!r} not registered — skipping call")
                    continue
                tool.call(args)
            except Exception as exc:  # noqa: BLE001
                push_log(state, f"  [error] tool dispatch failed: {exc}")
        state["tool_calls_pending"] = []
        return None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _looks_like_gibberish(text: str) -> bool:
    """Heuristically detect generation that's clearly off the rails.

    Memorised models can collapse to dominant-mode outputs when the
    prompt drifts even slightly from training distribution. Reject:

    * empty / whitespace-only
    * too few alphabetic characters (mostly punctuation)
    * a single character repeated past the threshold
    * starts with ``":"`` and contains no letters
    * too few unique tokens — e.g. ``"the"``, ``"the the the"``,
      ``"Ass\\n::\\nthe"`` (the collapse seen on real-robot frames
      where the model emits one or two memorised tokens repeatedly)
    * chat-template fragment leakage (``Assistant:``, ``User:``,
      ``Ass\\n``)

    Real subtasks look like ``"close the gripper to grasp the blue
    cube"`` — multiple unique alphabetic tokens, no role-marker
    fragments. Anything materially shorter than that is rejected.
    """
    if not text or not text.strip():
        return True
    stripped = text.strip()
    alpha = sum(1 for c in stripped if c.isalpha())
    if alpha < max(3, len(stripped) // 8):
        return True
    if stripped.startswith('":') and stripped.count('"') > stripped.count(" "):
        return True
    # Single repeating char: e.g. ``""""""``.
    if len(set(stripped)) <= 2 and len(stripped) > 4:
        return True
    # Chat-template fragment leakage — the model emits ``Ass``,
    # ``Assistant:``, ``User:``, often with extra newlines/colons.
    # Reject if the cleaned text is mostly role-marker shards.
    cleaned = stripped.replace("\n", " ").replace(":", " ")
    for marker in ("Assistant", "User", "Ass "):
        if marker in cleaned and len(cleaned.split()) < 4:
            return True
    tokens = [t for t in cleaned.split() if any(c.isalpha() for c in t)]
    unique_alpha = {t.lower() for t in tokens}
    # Short degenerate output — model stuck on ``the`` or a couple of
    # memorised single-token continuations.
    if len(unique_alpha) < 3 and len(stripped) < 80:
        return True
    # Long repetition collapse — the LM head loops an n-gram for the
    # whole generation budget ("the arm the arm … the the the the").
    # Length-independent: many tokens but a tiny unique ratio. The
    # earlier ``< 80`` check missed these because the looped string
    # blows well past 80 chars.
    if len(tokens) >= 8 and len(unique_alpha) <= max(3, len(tokens) // 10):
        return True
    return False


def _control_context_messages(
    state: dict[str, Any],
    *,
    include_completed: bool = False,
    extra_user: str | None = None,
) -> list[dict[str, Any]]:
    """Build a chat-template-ready prompt from current runtime state.

    Mirrors what ``subtasks_vqa.yaml`` renders into ``${task}\nPlan:
    ${plan}\nMemory: ${memory}`` for the high-level branches.
    """
    # Always emit ``Plan: `` / ``Memory: `` labels — even with empty
    # values — to mirror the training-time recipe substitution.
    task = state.get("task") or ""
    plan = state.get("current_plan") or ""
    memory = state.get("current_memory") or ""
    parts = [task, f"Plan: {plan}", f"Memory: {memory}"]
    if include_completed and state.get("current_subtask"):
        parts.append(f"Completed subtask: {state['current_subtask']}")
    head = "\n".join(parts)
    msgs: list[dict[str, Any]] = [{"role": "user", "content": head}]
    if extra_user:
        msgs.append({"role": "user", "content": extra_user})
    return msgs


# ---------------------------------------------------------------------------
# Per-recipe prompt builders. Each one mirrors a single sub-recipe's
# message layout in ``subtasks_vqa.yaml`` so the chat-templated
# prompt at inference matches what the model saw during training.
# Generic ``_control_context_messages`` is kept around as a fallback
# for ad-hoc callers but the four high-level steps now use these.
# ---------------------------------------------------------------------------


def _hirobot_user_head(state: dict[str, Any]) -> str:
    """Build the ``task\\nPlan: …\\nMemory: …`` user content string.

    Mirrors what the recipe renders at training time, where
    ``language_render._substitute`` substitutes empty strings for
    missing ``${plan}`` / ``${memory}`` bindings — i.e. the
    ``Plan: `` / ``Memory: `` prefix labels are *always* in the
    user turn, even when their values aren't set yet. Skipping them
    here (the previous behaviour) produced a different prompt shape
    on early frames before plan / memory are populated and on
    samples where the dataset has no plan / memory annotation.
    """
    task = state.get("task") or ""
    plan = state.get("current_plan") or ""
    memory = state.get("current_memory") or ""
    return f"{task}\nPlan: {plan}\nMemory: {memory}"


def _msgs_for_subtask(state: dict[str, Any]) -> list[dict[str, Any]]:
    """``high_level_subtask`` recipe layout — predict the subtask from the
    task. The v-current recipe's user turn is just ``${task}`` (plan and
    memory are not trained), so the inference prompt is the bare task —
    no ``Plan: `` / ``Memory: `` lines.
    """
    return [{"role": "user", "content": state.get("task") or ""}]


def _msgs_for_memory(state: dict[str, Any]) -> list[dict[str, Any]]:
    """Memory-update prompt — mirrors ``memory_update`` recipe layout.

    Recipe layout (``subtask_mem.yaml``):

        user:      "${task}"
        assistant: "Previous memory: ${prior_memory}"     (if_present prior)
        user:      "Completed subtask: ${completed}"       (if_present completed)
        assistant: → predicts new memory

    Fired by ``MemoryUpdateFwd`` on a ``subtask_change`` event:
    ``state['current_memory']`` is the memory the policy last emitted
    (= the ``prior_memory`` binding at training), and
    ``state['prior_subtask']`` is the subtask that just got replaced
    (= the ``completed_subtask`` binding at training).
    """
    msgs: list[dict[str, Any]] = [
        {"role": "user", "content": state.get("task") or ""},
    ]
    prior_memory = state.get("current_memory")
    if prior_memory:
        msgs.append(
            {"role": "assistant", "content": f"Previous memory: {prior_memory}"}
        )
    completed_subtask = state.get("prior_subtask")
    if completed_subtask:
        msgs.append(
            {"role": "user", "content": f"Completed subtask: {completed_subtask}"}
        )
    return msgs


def _msgs_for_interjection(state: dict[str, Any]) -> list[dict[str, Any]]:
    """``user_interjection_response`` recipe layout."""
    msgs: list[dict[str, Any]] = [
        {"role": "user", "content": state.get("task") or ""}
    ]
    if state.get("current_plan"):
        msgs.append(
            {"role": "assistant", "content": f"Previous plan:\n{state['current_plan']}"}
        )
    interjection = state.get("recent_interjection")
    if interjection:
        msgs.append({"role": "user", "content": interjection})
    return msgs


def _msgs_for_plan(state: dict[str, Any]) -> list[dict[str, Any]]:
    """``plan_generation`` recipe layout — bare task → plan.

    The assistant turn is the generation target, so we only render
    the user turn at inference; the runtime appends the predicted
    plan after sampling.
    """
    return [{"role": "user", "content": state.get("task") or ""}]


def _msgs_for_vqa(question: str) -> list[dict[str, Any]]:
    """``ask_vqa_*`` recipe layout (text-only at inference)."""
    return [{"role": "user", "content": question}]


def _maybe_observation(provider: Any) -> dict | None:
    """Pull one observation from ``provider`` if it's set, else ``None``.

    Errors from the provider are logged at debug level and swallowed —
    text generation still runs (in text-only mode) so a flaky frame
    source doesn't kill the REPL.
    """
    if provider is None:
        return None
    try:
        return provider()
    except Exception as exc:  # noqa: BLE001
        logger.debug("observation_provider raised %s — falling back to text-only", exc)
        return None


def _generate_with_policy(
    policy: Any,
    messages: list[dict[str, Any]],
    *,
    observation: dict | None = None,
    state: dict[str, Any] | None = None,
    label: str = "select_message",
    min_new_tokens: int = 0,
    temperature: float = 0.0,
    top_p: float = 1.0,
    suppress_loc_tokens: bool = False,
) -> str:
    """Drive ``policy.select_message`` with a chat batch (and optional obs).

    When ``observation`` carries ``observation.images.*`` and
    ``observation.state``, those are merged into the batch so
    ``select_message`` runs the same VLM prefix the policy was trained
    on. Without an observation the runtime falls back to a text-only
    prompt — the text head still runs, but generations may drift from
    the training distribution.

    Failures are surfaced both to the module logger (``warning``) and,
    when ``state`` is given, to the runtime's user-visible log via
    :func:`push_log`, so the REPL no longer "looks dead" when
    something goes wrong inside generation.
    """
    if not hasattr(policy, "select_message"):
        if state is not None:
            push_log(state, f"  [warn] policy has no select_message — skipping {label}")
        return ""
    text_batch = _build_text_batch(policy, messages)
    try:
        from lerobot.utils.constants import (  # noqa: PLC0415
            OBS_LANGUAGE_ATTENTION_MASK,
            OBS_LANGUAGE_TOKENS,
        )

        batch: dict[str, Any] = {
            OBS_LANGUAGE_TOKENS: text_batch["lang_tokens"],
            OBS_LANGUAGE_ATTENTION_MASK: text_batch["lang_masks"],
        }
        if observation:
            for k, v in observation.items():
                if isinstance(k, str) and k.startswith("observation.") and k not in batch:
                    batch[k] = v
        kwargs: dict[str, Any] = {
            "tokenizer": text_batch["tokenizer"],
            "min_new_tokens": min_new_tokens,
            "temperature": temperature,
            "top_p": top_p,
        }
        # Only pass ``suppress_loc_tokens`` to backbones that accept it
        # (pi052). SmolVLA2's ``select_message`` does not, so we omit
        # the kwarg there to avoid breaking the shared runtime.
        import inspect  # noqa: PLC0415

        if "suppress_loc_tokens" in inspect.signature(policy.select_message).parameters:
            kwargs["suppress_loc_tokens"] = suppress_loc_tokens
        return policy.select_message(batch, **kwargs)
    except Exception as exc:  # noqa: BLE001
        logger.warning("%s failed: %s", label, exc, exc_info=logger.isEnabledFor(logging.DEBUG))
        if state is not None:
            push_log(state, f"  [warn] {label} failed: {type(exc).__name__}: {exc}")
        return ""


_SAY_RE = re.compile(r"<\s*say\s*>(.*?)<\s*/\s*say\s*>", re.IGNORECASE | re.DOTALL)


def _split_plan_and_say(text: str) -> tuple[str, str]:
    """Pull a ``<say>...</say>`` snippet out of ``text``; remainder is plan.

    The training-time tool-call serializer wraps ``say(text="…")`` in a
    deterministic textual marker so prefix-LM-style training learns to
    emit it. The runtime parses it back here. If no marker is present,
    the entire text is treated as plan with no speech.
    """
    if not text:
        return "", ""
    match = _SAY_RE.search(text)
    if not match:
        return text.strip(), ""
    speech = match.group(1).strip().strip('"').strip("'")
    plan = (text[: match.start()] + text[match.end() :]).strip()
    return plan, speech
